name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install dependencies
        run: |
          go mod tidy
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Build
        run: make build

      - name: Test
        run: make test
